- hosts: webservers  

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install docker and configure docker user
      import_role: 
        name: geerlingguy.docker
      become: yes

    - name: Set allow ports for firewall
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      become: yes
      loop:
        - 22
        - 80
        - 443
        - 8080

    - name: Allow Node Exporter and prometheus port to prometheus server
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
        from_ip: "{{ private_ip_monitoring }}"
      become: yes
      loop:
        - 9090
        - 9100

    - name: Set default incoming policy firewall
      community.general.ufw:
        direction: incoming
        policy: deny
      become: yes

    - name: Set default outgoing policy firewall
      community.general.ufw:
        direction: outgoing
        policy: allow
      become: yes

    - name: Enable firewall
      community.general.ufw:
        state: enabled
      become: yes

    - name: Deploy and run app on server
      import_role: 
        name: deploy
      become: yes

    - name: Install observability Node Exporter
      import_role: 
        name: "node_exporter"
      become: yes